/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for kittyMusiCraft
**
 *  Copyright (c) 2022 LiveForIt Software.
 *  MIT License..
*/

#include <exec/types.h>
#include <libraries/kittyTurbo.h>

#include <interfaces/kittyMusiCraft.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

/****************************************************************************/

struct Library * kittyMusiCraftBase = NULL;
static struct Library * __kittyMusiCraftBase = NULL;

/****************************************************************************/

void kittyMusiCraft_base_constructor(void)
{
    if (kittyMusiCraftBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __kittyMusiCraftBase = kittyMusiCraftBase = IExec->OpenLibrary("kittymusicraft.library", 0);
    if (kittyMusiCraftBase == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to open 'kittymusicraft.library'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzz"))) static void
(*kittyMusiCraft_base_constructor_ptr)(void) USED = kittyMusiCraft_base_constructor;

/****************************************************************************/

void kittyMusiCraft_base_destructor(void)
{
    if (__kittyMusiCraftBase != NULL)
    {
        IExec->CloseLibrary(__kittyMusiCraftBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*kittyMusiCraft_base_destructor_ptr)(void) USED = kittyMusiCraft_base_destructor;

/****************************************************************************/

