
/* This file was generated by idltool 53.24. Do not edit */

#include "kittyMusiCraft_vectors.h"

STATIC uint32 VARARGS68K _kittymusicraft_UNIMPLEMENTED(struct kittyMusiCraftIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _kittymusicraft_Obtain,
    _kittymusicraft_Release,
    _kittymusicraft_UNIMPLEMENTED, /* Expunge */
    _kittymusicraft_UNIMPLEMENTED, /* Clone */
    _kittymusicraft_makeLookupTable,
    _kittymusicraft_FreeLookupTable,
    _kittymusicraft_makeContext,
    _kittymusicraft_FreeContext,
    (APTR)-1
};
