
/* This file was generated by idltool 53.24. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef LIBRARIES_KITTYTURBO_H
#include <libraries/kittyTurbo.h>
#endif

/* forward declaration */
struct kittyMusiCraftIFace;

extern ULONG                VARARGS68K _kittymusicraft_Obtain(struct kittyMusiCraftIFace *);
extern ULONG                VARARGS68K _kittymusicraft_Release(struct kittyMusiCraftIFace *);
extern char *               VARARGS68K _kittymusicraft_makeLookupTable(struct kittyMusiCraftIFace *);
extern void                 VARARGS68K _kittymusicraft_FreeLookupTable(struct kittyMusiCraftIFace *, void * table);
extern void *               VARARGS68K _kittymusicraft_makeContext(struct kittyMusiCraftIFace *);
extern void                 VARARGS68K _kittymusicraft_FreeContext(struct kittyMusiCraftIFace *, void * table);
