#ifndef KITTYMUSICRAFT_INTERFACE_DEF_H
#define KITTYMUSICRAFT_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.24.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYTURBO_H
#include <libraries/kittyTurbo.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct kittyMusiCraftIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct kittyMusiCraftIFace *Self);
	ULONG APICALL (*Release)(struct kittyMusiCraftIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	char * APICALL (*makeLookupTable)(struct kittyMusiCraftIFace *Self);
	void APICALL (*FreeLookupTable)(struct kittyMusiCraftIFace *Self, void * table);
	void * APICALL (*makeContext)(struct kittyMusiCraftIFace *Self);
	void APICALL (*FreeContext)(struct kittyMusiCraftIFace *Self, void * table);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* KITTYMUSICRAFT_INTERFACE_DEF_H */
